name: 'supply_chain'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  supply_chain:
    raw:
      +materialized: table
      +database: supply_chain
      +schema: raw
      description: "Raw layer that contains unprocessed data directly ingested from the source systems."

    silver:
      +materialized: table
      +database: supply_chain
      +schema: silver
      description: "Cleansed and transformed intermediate layer; includes deduplication, enrichment, and timestamp additions."

    gold:
      +materialized: table
      +database: supply_chain
      +schema: gold
      description: "Final reporting-ready data mart layer optimized for business users with dimensional models and aggregations."

seeds:
  my_new_project:
    warehouse_locations:
      +database: supply_chain
      +schema: raw
      +quote_columns: false
      +column_types:
        city_name: VARCHAR(50)
        state_name: VARCHAR(50)
        region: VARCHAR(20)
        warehouse_name: VARCHAR(50)
      +post-hook:
        - >
          INSERT INTO SUPPLY_CHAIN.AUDIT.MODEL_EXECUTION_LOG (
            model_name,
            load_date,
            row_count,
            file_name,
            last_modified,
            status,
            comments
          )
          SELECT
            'warehouse_locations',
            CURRENT_TIMESTAMP,
            COUNT(*),
            'warehouse_locations.csv',
            CURRENT_TIMESTAMP,
            'SUCCESS',
            'Seed loaded via dbt seed'
          FROM SUPPLY_CHAIN.DEV__RAW.WAREHOUSE_LOCATIONS
          WHERE NOT EXISTS (
            SELECT 1
            FROM SUPPLY_CHAIN.AUDIT.MODEL_EXECUTION_LOG
            WHERE model_name = 'warehouse_locations'
              AND row_count = (SELECT COUNT(*) FROM SUPPLY_CHAIN.DEV__RAW.WAREHOUSE_LOCATIONS))
      description: "Seed data for warehouse location metadata used in regional sales and logistics analytics."

snapshots:
  my_new_project:
    customer:
      +schema: silver
      description: "Snapshot to capture historical changes in customer order data for SCD2 tracking."

    inventory:
      +schema: silver
      description: "Snapshot to track historical changes in item inventory records, supporting time-travel insights."

